### ISSUE TITLE
Create TX2 supported kiss file

### ISSUE THREAD

**Issue by SteveJos** [yankailab/OpenKAI#11]
Add TX2 (JetPack 3.0) compatibility to the project

**Comment by yankailab** [comment]
At the moment it should work with JetPack 3.0 on TX1, which I've tested.
Working on TX2, just received my TX1 few days ago and playing with it.

**Comment by SteveJos** [comment]
Unfortunately I get the following error code:

> I0717 12:12:28.961537  6964 APcopter_base.cpp:86] apBase: pCC->v("lim", &cPID.m_lim)
ZED (Init) >> Depth mode: Performance
ZED (Init) >> Video mode: VGA@60
OpenCV Error: Gpu API call (invalid device function) in call, file /hdd/buildbot/slave_jetson_tx_3/35-O4T-L4T-R24/opencv/modules/gpu/include/opencv2/gpu/device/detail/transform_detail.hpp, line 320
terminate called after throwing an instance of 'cv::Exception'
  what():  /hdd/buildbot/slave_jetson_tx_3/35-O4T-L4T-R24/opencv/modules/gpu/include/opencv2/gpu/device/detail/transform_detail.hpp:320: error: (-217) invalid device function in function call
>
>Aborted (core dumped)

I installed everything as default and compiled without errors. Maybe you could provide further explanation?  Furthermore if I undo your commit: "Updated apCopter.kiss for TX1" and change the ZED settings no error occur but I see a black window with Text overlay:

![screenshot from 2017-07-17 12-18-26](https://user-images.githubusercontent.com/23660491/28267787-25b9d5ca-6aeb-11e7-92a5-76cee57d36b7.png)


How do I get the videostream of ZED in the settings of the kiss file? 
Thank you in advance!

**Comment by SteveJos** [comment]
@yankailab do you maybe have any idea what could be wrong?

**Comment by yankailab** [comment]
@SteveJos the apCopter.kiss might be out of date due to some recent update, lemme have a look, will try to solve it soon.

**Comment by yankailab** [comment]
install script for TX2 (tested on JetPack 3.2)
https://github.com/yankailab/OpenKAI/blob/master/sh/Install/OpenKAI_install_TX2.sh
